Repository nglcobdai/typing-game, pull requests merged in 2023-06, with the labels that each got.

#6 Storybook に関するルールのドキュメントの追加
  docs/coding-rule.md
Labels: documentation

#7 文字とボタンを組み合わせたコンポーネントの作成
  README.md
  components/CustomTextButton/index.stories.tsx
  components/CustomTextButton/index.tsx
Labels: feature, ui・ux

#17 タブキー入力で適切な無視ができていない
  components/CodeBlock/index.tsx
Labels: bug, ui・ux

#19 問題の表示を左揃えに変更する
  components/CodeBlock/index.tsx
Labels: bug, ui・ux

#16 ページの組み上げ
  components/CodeBlock/index.stories.tsx
  components/CodeBlock/index.tsx
  pages/index.tsx
Labels: feature, ui・ux, block
